package com.moreapp.demo;


import com.moreapp.demo.R;

import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import android.os.Build;

public class Terms extends Fragment {

	@Override
	public View onCreateView(LayoutInflater inflater, ViewGroup container,
			Bundle savedInstanceState) {
		View view = inflater.inflate(R.layout.activity_privacy, null);
		TextView txt1 = (TextView) view.findViewById(R.id.textView1);
		TextView txt2 = (TextView) view.findViewById(R.id.textView2);
		TextView txt3 = (TextView) view.findViewById(R.id.textView3);
		TextView txt4 = (TextView) view.findViewById(R.id.textView4);
		TextView txt5 = (TextView) view.findViewById(R.id.textView5);
		TextView txt6 = (TextView) view.findViewById(R.id.textView6);
		TextView txt7 = (TextView) view.findViewById(R.id.textView7);
		TextView txt8 = (TextView) view.findViewById(R.id.textView8);
		TextView txt9 = (TextView) view.findViewById(R.id.textView9);
		TextView txt10 = (TextView) view.findViewById(R.id.textView10);
		TextView txt11 = (TextView) view.findViewById(R.id.textView11);
		TextView txt12 = (TextView) view.findViewById(R.id.textView12);
		TextView txt13 = (TextView) view.findViewById(R.id.textView13);
		TextView txt14 = (TextView) view.findViewById(R.id.textView14);
		TextView txt15 = (TextView) view.findViewById(R.id.textView15);
		TextView txt16 = (TextView) view.findViewById(R.id.textView16);
		TextView txt17 = (TextView) view.findViewById(R.id.textView17);
		TextView txt18 = (TextView) view.findViewById(R.id.textView18);
		TextView txt19 = (TextView) view.findViewById(R.id.textView19);
		TextView txt20 = (TextView) view.findViewById(R.id.textView20);
		TextView txt21 = (TextView) view.findViewById(R.id.textView21);
		TextView txt22 = (TextView) view.findViewById(R.id.textView22);
		TextView txt23 = (TextView) view.findViewById(R.id.textView23);
		TextView txt24 = (TextView) view.findViewById(R.id.textView24);
		TextView txt25 = (TextView) view.findViewById(R.id.textView25);
		TextView txt26 = (TextView) view.findViewById(R.id.textView26);
		TextView txt27 = (TextView) view.findViewById(R.id.textView27);
		TextView txt28 = (TextView) view.findViewById(R.id.textView28);
		
		txt1.setText("\nMORE HEALTH INC. TERMS OF USE\n");
		txt2.setText("\nPLEASE READ THESE TERMS AND CONDITIONS OF USE CAREFULLY BEFORE USING THIS SITE AND/OR APP.\n" +
				"\nThe Terms of Use (or \"TOU\") is an agreement between you and MORE Health, Inc. (\"MORE\"). There are rules you agree to follow when using our mobile applications and websites (the \"Apps\"), including when you ask questions and when you view or input content on or into the Apps, and these rules are contained in these TOU. The MORE Privacy Statement is officially part of these TOU even though it’s a separate document.\n");
		txt3.setText("\nI. MORE is NOT a Healthcare Provider.\n");
		txt4.setText("\nPlease be aware that any information offered to you through the Apps is provided to aid you on your travels. It is neither intended nor implied to be a substitute for professional medical advice. CALL YOUR HEALTHCARE PROVIDER IMMEDIATELY IF YOU THINK YOU MAY HAVE A MEDICAL EMERGENCY.\n" +
				"\nAlways seek the advice of your physician or other qualified healthcare provider prior to starting any new exercise, diet, or treatment.  MORE DOES NOT PROVIDE MEDICAL DIAGNOSIS, TREATMENT, OR PRESCRIPTION OF ANY KIND. ALL INFORMATION PROVIDED ON MORE OR IN CONNECTION WITH ANY COMMUNICATIONS SUPPORTED BY MORE, INCLUDING BUT NOT LIMITED TO COMMUNICATIONS BETWEEN MORE AND CONSUMERS IS INTENDED TO BE FOR GENERAL INFORMATIONAL PURPOSES ONLY, AND IS IN NO WAY INTENDED TO CREATE A PHYSICIAN – PATIENT RELATIONSHIP AS DEFINED BY STATE AND FEDERAL LAW. MORE IS NOT A SUBSTITUTE FOR PROFESSIONAL MEDICAL DIAGNOSIS OR TREATMENT. RELIANCE ON ANY INFORMATION PROVIDED BY MORE OR ANY PERSON OR ENTITY AFFILIATED WITH MORE IS SOLELY AT YOUR OWN RISK.  Please ask your physician or other qualified healthcare provider any questions you may have regarding a medical condition.\n" +
				"\nNeither MORE, any of its affiliates, and any vendors or suppliers of content provided through the Apps, nor any of their respective directors, officers, employees or agents, shall be liable in any way for any use by you or anybody of information provided through the Apps, and none of them make any warranty or guaranty as to the accuracy, completeness, correctness, timeliness, or usefulness of any content provided on the Apps. You may use the Apps and the information contained on them solely at your own sole risk.\n");
		txt5.setText("\nII. Children's Privacy.\n");
		txt6.setText("\nWe are committed to protecting the privacy of children. You should be aware that the Apps are not intended or designed to attract children under the age of 13. We do not collect personally identifiable information from any person we actually know is a child under the age of 13. \n");
		txt7.setText("\nIII. Your Account and Use of MORE.\n");
		txt8.setText("\nAccurate and complete registration information is required to use MORE. Only you may use your account credentials. You must keep your account credentials confidential and not authorize anyone else to access or use the service on your behalf, unless we provide an approved mechanism for that. You must contact Customer Support right away if you suspect misuse of your account or any security breach in the service. You are responsible for all activity that takes place with your service account.\n" +
				"\nYour use of MORE and any Content and Services must comply with all applicable federal and state laws, regulations, and ordinances. Currently, you must be at least 18 years old to use MORE.\n" +
				"\nWhen you register as a member, you agree that MORE may send notices to you by email at the email address you provide when you register, or a different email address that you update through your Account Settings. We have a No-Spam policy.\n");
		txt9.setText("\nIV. Internet Access May Be Required.\n");
		txt10.setText("\nTo access the Apps by means of a cellular data connection on a portable device (such as an iPhone), you will need a data access plan from your wireless carrier. In order to access the Apps via WiFi or Internet connection, you will need a compatible device, software, browser and Internet access. Check with your provider to learn if any fees apply. You are solely responsible for any fees or costs you incur to access the Apps through any wireless or other communication service. \n");
		txt11.setText("\nV. Your Content and Records.\n");
		txt12.setText("\nWe don't claim ownership of the content you provide on the service. Your content remains your content. We also don't control, verify, or endorse the content that you and others make available on the service.\n" +
				"\nYou control who may access your content, along with any co-custodians and other invited users. If you share content in your records, then you agree that anyone you've shared content with may use that content. When you give others access to your content on the service, they can use, reproduce, distribute, display, transmit, and communicate to the public the content. If you don't want others to have that ability, don't use the service to share your content.\n" +
				"\nIf you share content on the service in a way that infringes others' rights, including privacy rights, you're breaching this contract. You represent and warrant that you have all the rights necessary for you to grant the rights in this section and the use of the content doesn't violate any law. We may remove your content from the service at any time if you breach this contract.\n" +
				"\nYou're responsible for backing up the data that you store on the service. If your service is canceled, we may permanently delete your data from our servers. We have no obligation to return data to you after the service is canceled. If data is stored with an expiration date, we may also delete the data as of that date. Deleted data may be irretrievable.\n" +
				"\nThe service is intended for travel use. It does not hold records for healthcare providers or other medical or case management purposes. For example, MORE records are not designated record sets as defined under U.S. Regulations. If a healthcare provider decides to include any data made available from MORE in its records, it should store a copy in its own system.\n" +
				"\nMORE is a service for individuals to personally use in travel. You may use MORE for personal, but not for commercial, purposes. Organizations, companies, and businesses may not become registered members or use our Apps through individual members. We authorize you to view or download the Content and use the Services solely for your personal, noncommercial use in accordance with all applicable federal, state and local laws. The Content is licensed only for the personal, household, and educational use of a single individual. An individual's noncommercial reuse or redistribution of any portion of the Content is permitted when that use falls within what is permitted by United States Copyright law or the Lanham Act. These laws govern general personal use of copyrighted information. No commercial use or redistribution of any Content is permitted. Any hyperlink or other re-display of the information on another website must display the Content full-screen and not within a \"frame\" on the linked or other site, unless expressly pre-approved and permitted by us in writing. By using MORE, you agree not to use any contact information provided by members (for example, in a private message exchange between connected members), or harvest, scrape or otherwise collect any information about our members for any reason, including but not limited to for sending unsolicited communications, including spam. \n" +
				"\nWe do not recommend or endorse any specific Content, Services, tests, physicians, products, procedures, opinions, or other information that may be mentioned on MORE. \n" +
				"\nMORE is designed to be used with common sense, and in connection with the advice of your physician or your other healthcare provider. Reliance on MORE Content or Services is solely at your own risk. We work hard to bring you our very best, and believe that our members will find the Content and Services useful, but we cannot guarantee that the Content and Services will help you achieve any specific goals or results.\n" +
				"\nNow or in the future, the Content and Services may link you to other websites or information, software, data, or other contents, on or off the Internet. These other sites or and contents are not MORE, and the information there is outside of our control. We do not control, endorse, or review the content of these sites. We do not review the contents that may be reached by such links, and we are not responsible for such content. The information, software, data, or other contents (including opinions, claims, comments) contained in linked references are those of the companies responsible for such sites, and should not be attributed to us. We have not attempted to verify the truth or accuracy of any such opinion, claim, or comment, nor do we endorse or support them. We do not warrant, nor are we in any way responsible for, information, software, data, privacy policies, or other content that is outside of our control.\n" +
				"\nThe Content and Services may not be used for any illegal purpose. You may not access our networks, computers, or the Content and Services in any manner that could damage, disable, overburden, or impair them, or interfere with any other person's use and enjoyment. You may not attempt to gain unauthorized access to any Content or Services, other accounts, computer systems, or networks connected with MORE, the Content, or Services. You may not use any automated means (such as a scraper) to access MORE, the Content, or Services for any purpose. Such unauthorized access includes, but is not limited to, using another person’s login credentials to access his or her MORE account. Any attempt by any individual or entity to solicit login information of any other user or to access any such account is an express and direct violation of these Terms of Use and of applicable law, including relevant privacy and security laws and laws prohibiting unfair or unethical business practices. \n" +
				"\nIf you violate any of these Terms of Use, your permission to use the Content and Services automatically terminates and you must immediately destroy any copies you have made of any portion of the Content.\n");
		txt13.setText("\nVI. Intellectual Property.\n");
		txt14.setText("\nAll software and content included on these Apps or used in the operation of the Apps is the owned or licensed property of MORE or its software and content suppliers and protected by U.S. and international copyright laws. The compilation (meaning the collection, arrangement, and assembly) of all content on the Apps is the exclusive property of MORE and protected by U.S. and international copyright laws. MORE grants you permission to view and use content and software made available to you on the Apps in connection with your own personal, noncommercial use of the Apps. Any other use, including the reproduction, modification, distribution, transmission, republication, display, or performance, of the content and software on the Apps is strictly prohibited. \n" +
				"\nThe trademarks, service marks, trade dress, and “look and feel” (the \"Trademarks\") used and displayed on the Apps are registered and unregistered Trademarks of MORE and others. Nothing on the Apps shall be construed as granting, by implication, estoppel or otherwise, any license or right to use any Trademark displayed on the Aps, without the prior written permission of the Trademark owner. Other product and company names mentioned in the Apps may be the Trademarks of their respective owners. \n");
		txt15.setText("\nVII. International Members.\n");
		txt16.setText("\nWe make no claim that Content or Services are appropriate or may be downloaded outside of the United States. Personal information (\"Information\") that is submitted to MORE will be collected, processed, stored, disclosed and disposed of in accordance with applicable U.S. law and our Privacy Statement. If you are a non-U.S. member, you acknowledge and agree that MORE may collect and use your Information and disclose it to other entities outside your resident jurisdiction. In addition, such Information may be stored on servers located outside your resident jurisdiction. U.S. law may not provide the degree of protection for Information that is available in other countries. By providing us with your Information, you acknowledge that you consent to the transfer of such Information outside your resident jurisdiction as detailed in our Privacy Policy. If you do not consent to such transfer, you may not use our Content or Services. The product information provided on MORE is intended only for residents of the United States. Products identified on this site may have different product labeling and disclosure requirements in different countries. \n");
		txt17.setText("\nVIII. Indemnification.\n");
		txt18.setText("\nYou agree to indemnify, defend, and hold MORE and its successors and assigns harmless from and against and in respect of any and all third party claims, demands, losses, costs, expenses, obligations, liabilities, damages, recoveries, and deficiencies, including interest, penalties, and reasonable attorneys' fees that it shall incur or suffer which relate to your use of the Apps, your failure to perform any of your obligations under these Terms of Use, or your breach of any of your representations or warranties made under these Terms of Use. \n");
		txt19.setText("\nIX. Changes to This Agreement.\n");
		txt20.setText("\nWe may change this contract, and will notify you by posting new terms. If you do not agree to the changes, you must cancel and stop using the service. If you do not stop using the service, the new terms apply to you. \n");
		txt21.setText("\nX. No Warranty.\n");
		txt22.setText("\nWe provide the service \"as-is,\" \"with all faults\" and \"as available.\" The entire risk as to the quality and performance of the service and software is with you. Should the service or software prove defective, you assume the entire cost of all necessary servicing or repair. We don't guarantee the accuracy or timeliness of information available from the service. You acknowledge that computer and telecommunications systems are not fault-free and occasional periods of downtime occur. We do not guarantee the service will be uninterrupted, timely, secure, or error-free, or that data loss will not occur. We and our affiliates and vendors give no express warranties, guarantees, or conditions. We exclude any implied warranties, including for merchantability, satisfactory quality, fitness for a particular purpose, workmanlike effort, and noninfringement. You may have certain rights under your local law. Nothing in this contract is intended to affect those rights, if they are applicable.\n" +
				"\nThird-party programs and devices that connect with MORE are not endorsed or warranted by MORE. Product descriptions are by their manufacturers and provided for informational purposes only. These Apps do not provide medical or any other health care advice, diagnosis or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition, diet, fitness or wellness program. Never disregard professional medical advice or delay in seeking it because of information you accessed on or through the service.\n");
		txt23.setText("\nXI. Liability Information.\n");
		txt24.setText("\nIf you have any basis for recovering damages from MORE or its affiliates and vendors, you can recover only direct damages up to US $5.00. You cannot recover any other damages, including consequential, lost profits, special, indirect, incidental or punitive damages.\n" +
				"\nThe limitations and exclusions apply to anything related to this contract, such as loss of data; third-party content, programs or conduct; viruses that affect your use of the service; incompatibility between the service and other services, software and hardware; delays or failures you may have in starting or completing transmissions; and claims for breach of contract, warranty, guarantee or condition; consumer protection; deception; unfair competition; strict liability, negligence, misrepresentation, omission, trespass or other tort; violation of statute or regulation; or unjust enrichment; all to the extent permitted by applicable law.\n" +
				"\nThe limitations and exclusions also apply if this remedy does not fully compensate you for any losses or fails of its essential purpose or if we knew or should have known about the possibility of the damages.\n" +
				"\nNothing in these terms shall affect the statutory rights of any consumer or exclude or restrict liability for death or personal injury arising from our negligence, fraud, or our gross negligence or willful intent. Some or all of these limitations or exclusions may not apply to you if your state, province, or country does not allow the exclusion or limitation of incidental, consequential, or other damages.\n");
		txt25.setText("\nXII. Changes to the Service and Cancellation.\n");
		txt26.setText("\nWe continuously work to improve the service and may change the service at any time. Additionally, there are reasons why MORE may stop providing portions of the service, including (without limitation) that it's no longer feasible for us to provide it, the technology advances, customer feedback indicates a change is needed, or external issues arise that make it imprudent or impractical to continue. If your service is canceled, your right to use the service stops immediately. Your ability to access and use some third-party programs may also stop right away.\n" +
				"\nYou may cancel the service at any time and for any reason. Sections X-XIII, and those that by their terms apply after termination of this contract will survive any termination of this contract.\n");
		txt27.setText("\nXIII. General Legal Terms.\n");
		txt28.setText("\nThis Agreement, and the other agreements referenced in it (like our Privacy Policy), is the entire agreement between you and us relating to MORE. This Agreement replaces any prior agreements unless such prior or subsequent agreement explicitly provides otherwise and specifically references this Agreement. If there is any conflict between this Agreement and a mutually signed written agreement between you and us related to MORE, the signed written agreement will control.\n" +
				"\nOther parties may have rights under this Agreement. A \"third party beneficiary\" is another party (for example, a company) who is not directly mentioned in an agreement, but who may have some rights arising out of an agreement. Our licensors may be third party beneficiaries to this Agreement pursuant to our agreements with them. To the extent our licensors are third party beneficiaries to this Agreement, the rights and protections provided to us under this Agreement inure to their benefit. Other than these licensors, there are no other third party beneficiaries to this Agreement. The parties are independent contractors, and nothing in this Agreement creates an agency, partnership, or joint venture.\n" +
				"\nIf we provide you with a translation of the English language version of this Agreement, the English language version of this Agreement will control if there is any conflict.\n" +
				"\nIf we choose not to enforce any provision of this Agreement, we still keep the right to enforce it in the future. This means that the failure to enforce any provision of this Agreement does not constitute a waiver of that provision. If any provision in this Agreement is found to be unenforceable, it and any related provisions will be interpreted to best accomplish the unenforceable provision's essential purpose.\n" +
				"\nThis Agreement is governed by California law, excluding California's choice-of-law rules. THE EXCLUSIVE VENUE FOR ANY DISPUTE RELATING TO THIS AGREEMENT IS SAN MATEO COUNTY, CALIFORNIA. YOU AND US CONSENT TO THE PERSONAL JURISDICTION OF THESE COURTS. Nothing in this Agreement limits either party's ability to seek equitable relief.\n");
		return view;
	}

}
